# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66aaeb4bc2e525b87d550b5abc546aabe5306a305fdb659f972334365e33803d1640519201f3106385e48a8cdf2441ffb12325868fa3315fc2afdc5a9e3cd604

test:
  secret_key_base: 48740532b58ca29a12596b3749daa0d792095badec307f61b47c6c2d969d364ed4e8b99af65a4111fed283441e8530fb9bf06473cb01302bef4bd43d431bd672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
